### ISSUE TITLE
UserWarning - pkg_resources package is slated for removal as early as 2025-11-30

### ISSUE THREAD

**Issue by seebi** [smarie/python-genbadge#44]
The following warning appears when using genbadge:

```
.../.venv/lib/python3.11/site-packages/genbadge/utils_badge.py:20: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_string, resource_filename
```

**Comment by vonsteer** [comment]
FYI @smarie  Fixed the issue on #45 and tested it locally against some of my packages to be sure the warning is gone.
Also thanks for creating and continuing to maintain this library @smarie ! I use it on most of my projects.

**Comment by smarie** [comment]
Thanks for the warning @seebi ! And thanks a lot for the fix suggestion @vonsteer , I'll have a look asap

**Comment by vonsteer** [comment]
Updated the PR with the requested changes btw @smarie ! Also created [#46](https://github.com/smarie/python-genbadge/issues/46) for the other issue I fixed that was blocking this PR.

**Comment by lpravda** [comment]
I dont think has been merged and released, I can still see the warning with the currently released version. Is there any plan on merging and releasing it?

**Comment by smarie** [comment]
Hi there, let me check this out

**Comment by smarie** [comment]
Done - genbadge 1.1.3 is out with this fix. Sorry for the wait ! And thanks @vonsteer for the nice PR
